### Welcome
GET http://localhost:8080/api/

### GET All Soal
GET http://localhost:8080/api/question/all

### GET Soal by Id
GET http://localhost:8080/api/question/Lcfzhr40T37ufB6O8IhG

### POST Soal
POST http://localhost:8080/api/question
Content-Type: application/json

{
  "question": "Apakah anak Tidak melihat ketika namanya dipanggil",
  "category": "A4",
  "type": [
    "Speech/Language/Communication",
    "Sociability",
    "Sensori/Kognitif"
  ]
}