GET http://localhost:3000/api/user

### GET All User
GET http://localhost:3000/api/user/all

### GET User By Id
GET http://localhost:3000/api/user/6552501d7ca0188162ccca8c

### Create User
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "nama_lengkap" : "Prinafsika",
    "jenis_kelamin" : "L",
    "tanggal_lahir" : "2003-07-07",
    "tempat_lahir" : "Jakarta",
    "alamat" : "Indonesia"
}

### Update User
PUT http://localhost:3000/api/user/6552501d7ca0188162ccca8c
Content-Type: application/json

{
    "nama_lengkap" : "UpiN",
    "jenis_kelamin" : "P",
    "tanggal_lahir" : "2023-02-03",
    "tempat_lahir" : "Banten",
    "alamat" : "Indonesia"
}

### Delete User
DELETE http://localhost:3000/api/user/6552531566c32f622dc2951a