### GET All User
GET http://localhost:8080/api/user/all

### GET User by Id
GET http://localhost:8080/api/user/sJUBzpL17OhYldHKbL2Lkj05YRs1

### GET User by Email
GET http://localhost:8080/api/user/email/nap@napuniverse.me

### POST Register User
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
    "email":"fidelas@mail.com",
    "password":"12345678"
}

### UPDATE User
PUT http://localhost:8080/api/user/sJUBzpL17OhYldHKbL2Lkj05YRs1
Content-Type: application/json

{
    "email":"inapzky@napuniverse.me",
    "password":"testp4ssw0rd"
}

### DELETE User
DELETE http://localhost:8080/api/user/dAwxlFUKkhQfiJr08Pi0H0K95eB3