@base_url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRTU2lUSjdnTEQ3aXVOaFhIenFiR0h1OVFFTFkuUlZsTkwxbXNxTnlEcjhOVkFxVTBBZ0VYNiIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjEyMzQ1Njc4IiwiZW1haWwiOiJvbmVzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJvbmUiLCJpYXQiOjE3MDI1NzQwMDN9.ZjD3Q3FqN4tAqxh2L0VSscx-mayO0U0zkYB35zfGalo

### GET All Therapy
GET {{base_url}}/api/therapy/all
Content-Type: application/json
Authorization: Bearer {{token}}

### GET Therapy by Id
GET {{base_url}}/api/therapy/MyCAK7CmRVcj26VlDoXG
Content-Type: application/json
Authorization: Bearer {{token}}

### POST Therapy Recommendation
POST {{base_url}}/api/therapy
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "category": "A2",
  "type": [
    "Speech/Language/Communication",
    "Sociability",
    "Sensori/Kognitif"
  ],
  "therapy": {
    "name": "Menirukan suara hewan",
    "description": [
      "Ayah atau Ibu atau orang yang bertanggungjawab lainnya dapat memberikan anak mainan yang berupa hewan.",
      "Setiap bermain dengan mainan tersebut bersama anak, tirukan suara dari hewan tersebut. (meong, mbeeek, dsb)",
      "Lakukan sesering mungkin, namun tidak terlalu lama (5-10 menit setiap hari).",
      "Jika dirasa tidak ada perubahan, silahkan pertemukan anak dengan orang profesional untuk penanganan lebih"
    ]
  }
}