@base_url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRTU2lUSjdnTEQ3aXVOaFhIenFiR0h1OVFFTFkuUlZsTkwxbXNxTnlEcjhOVkFxVTBBZ0VYNiIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjEyMzQ1Njc4IiwiZW1haWwiOiJvbmVzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJvbmUiLCJpYXQiOjE3MDI1NzQwMDN9.ZjD3Q3FqN4tAqxh2L0VSscx-mayO0U0zkYB35zfGalo

### GET User by Id
GET {{base_url}}/api/users/Z1KiPS9E4JDuGXG5T91Q
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRTU2lUSjdnTEQ3aXVOaFhIenFiR0h1OVFFTFkuUlZsTkwxbXNxTnlEcjhOVkFxVTBBZ0VYNiIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjEyMzQ1Njc4IiwiZW1haWwiOiJvbmVzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJvbmUiLCJpYXQiOjE3MDI1NzQwMDN9.ZjD3Q3FqN4tAqxh2L0VSscx-mayO0U0zkYB35zfGalo

### GET User by Email
GET {{base_url}}/api/users/email/onesimusx@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRTU2lUSjdnTEQ3aXVOaFhIenFiR0h1OVFFTFkuUlZsTkwxbXNxTnlEcjhOVkFxVTBBZ0VYNiIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjEyMzQ1Njc4IiwiZW1haWwiOiJvbmVzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJvbmUiLCJpYXQiOjE3MDI2NzU4NjMsImV4cCI6MTcwMjY3OTQ2M30.vf9cz6HNset3UEZmIK2LLLJTwnodfwRSQ0pyW2io9zE

### POST login
POST {{base_url}}/api/users/login
Content-Type: application/json

{
    "identifier":"onesimusx@gmail.com",
    "password":"12345678"
}

### PUT User by Id
PUT {{base_url}}/api/users/update/Z1KiPS9E4JDuGXG5T91Q
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRTU2lUSjdnTEQ3aXVOaFhIenFiR0h1OVFFTFkuUlZsTkwxbXNxTnlEcjhOVkFxVTBBZ0VYNiIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjEyMzQ1Njc4IiwiZW1haWwiOiJvbmVzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJvbmUiLCJpYXQiOjE3MDI2NzU4NjMsImV4cCI6MTcwMjY3OTQ2M30.vf9cz6HNset3UEZmIK2LLLJTwnodfwRSQ0pyW2io9zE

{
    "username" : "one",
    "email" : "onesimus@gmail.com",
    "domicile":  "sulawesi",
    "birthDate" : "123456"
}

### DELETE User
DELETE {{base_url}}/api/users/delete/Z1KiPS9E4JDuGXG5T91Q

### POST LOGOUT
POST {{base_url}}/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRTU2lUSjdnTEQ3aXVOaFhIenFiR0h1OVFFTFkuUlZsTkwxbXNxTnlEcjhOVkFxVTBBZ0VYNiIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjEyMzQ1Njc4IiwiZW1haWwiOiJvbmVzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJvbmUiLCJpYXQiOjE3MDI2NzU4NjMsImV4cCI6MTcwMjY3OTQ2M30.vf9cz6HNset3UEZmIK2LLLJTwnodfwRSQ0pyW2io9zE

### POST REGISTER Data user
POST {{base_url}}/api/users/register
Content-Type: application/json

{
    "username" : "four",
    "email" : "foursimusx@gmail.com",
    "domicile" :  "jakarta",
    "birthDate" : "01/01/2001",
    "password" :  "12345678",
    "confirmPass" : "12345678"
}