@base_url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRTU2lUSjdnTEQ3aXVOaFhIenFiR0h1OVFFTFkuUlZsTkwxbXNxTnlEcjhOVkFxVTBBZ0VYNiIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjEyMzQ1Njc4IiwiZW1haWwiOiJvbmVzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJvbmUiLCJpYXQiOjE3MDI1NzQwMDN9.ZjD3Q3FqN4tAqxh2L0VSscx-mayO0U0zkYB35zfGalo

### GET All Child
GET {{base_url}}/api/child/all
Content-Type: application/json
Authorization: Bearer {{token}}

### GET Child by Id
GET {{base_url}}/api/child/DndDLpRT4195V69kVTWJ
Content-Type: application/json
Authorization: Bearer {{token}}

### POST Data Child
POST {{base_url}}/api/child
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "XxxX",
    "born": "30/02/2077",
    "city": "Cyber park",
    "gender": "Boys",
    "diagnose": "Little Crazy",
    "recommendation": [
        "Speech therapy",
        "Social therapy"
    ]
}

### UPDATE Child
PUT {{base_url}}/api/child/DndDLpRT4195V69kVTWJ
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "xVFx",
    "born": "30/02/2077",
    "city": "Cyber park",
    "gender": "Boys",
    "diagnose": "Little Crazy",
    "recommendation": [
        "Speech therapy",
        "Social therapy"
    ]
}

### DELETE Child
DELETE {{base_url}}/api/child/KWFyFGxUogkQAU7GdjQ8
Content-Type: application/json
Authorization: Bearer {{token}}