@base_url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRCWlUzVjFkVGxmZ1ZHVDFvQUpWdWhPNHdrSWwvS2hKdS5vTDkzLk5wYjFHZlhPbGM4anZmeSIsImRvbWljaWxlIjoiamFrYXJ0YSIsImJpcnRoRGF0ZSI6IjAxLzAxLzIwMDEiLCJlbWFpbCI6ImZvdXJzaW11c3hAZ21haWwuY29tIiwidXNlcm5hbWUiOiJmb3VyIiwiaWF0IjoxNzAyODE4NjIxLCJleHAiOjE3MDI4MjIyMjF9.GlQhGYSJnvznMOEZIHHEQ6DE9REuLR6-LXUZdEe7Z88

### Welcome
GET {{base_url}}/api/

### GET All Soal
GET {{base_url}}/api/question/all
Content-Type: application/json
Authorization: Bearer {{token}}

### GET Soal by Id
GET {{base_url}}/api/question/5Z8t1e7aEGgDUafSdAN0
Content-Type: application/json
Authorization: Bearer {{token}}

### POST Soal
POST {{base_url}}/api/question
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "question": "Apakah anak Tidak melihat ketika namanya dipanggil",
  "category": "A50",
  "type": [
    "Speech/Language/Communication",
    "Sociability",
    "Sensori/Kognitif"
  ]
}