@base_url = http://34.128.115.4
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6IiQyYiQxMCRheVI2R0VKZ043OGNSbkV5S2NTUDJleHdTbmJSTXVOOThWZnREZlJCZXhKaFBPY3laWnpaSyIsImVtYWlsIjoieWFudG9AZ21haWwuY29tIiwiZG9taWNpbGUiOiJiYW50ZW4iLCJiaXJ0aERhdGUiOiIxMjM0NTYiLCJ1c2VybmFtZSI6InlhbnRvIG9ueWEgZHVhIiwiaWF0IjoxNzAzMDU5MjMyLCJleHAiOjE3MDMwNjI4MzJ9.3czL_aPNVJN6OrWA2pAJ8ybTM0xe8Ber6J8qEWitctQ

### Welcome
GET {{base_url}}/api/

### GET All Soal
GET {{base_url}}/api/question/all
Content-Type: application/json
Authorization: Bearer {{token}}

### GET Soal by Id
GET {{base_url}}/api/question/5Z8t1e7aEGgDUafSdAN0
Content-Type: application/json
Authorization: Bearer {{token}}

### POST Soal
POST {{base_url}}/api/question
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "question": "Apakah anak Tidak melihat ketika namanya dipanggil",
  "category": "A50",
  "type": [
    "Speech/Language/Communication",
    "Sociability",
    "Sensori/Kognitif"
  ]
}